config/routes.rb
Rails.application.routes.draw do
  resources :campers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "campers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/camper.rb
class Camper < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/campers_controller.rb
class CampersController < ApplicationController
  before_action :set_camper, only: [:show, :edit, :update, :destroy]

  # GET /campers
  # GET /campers.json
  def index
    @campers = Camper.all
  end

  # GET /campers/1
  # GET /campers/1.json
  def show
    @camper = Camper.find(params[:id])
  end

  # GET /campers/new
  def new
    @camper = Camper.new
  end

  # GET /campers/1/edit
  def edit
    @camper = Camper.find(params[:id])
  end

  # POST /campers
  # POST /campers.json
  def create
    @camper = Camper.new(camper_params)

    @camper.save
    redirect_to @camper
  end

  # PATCH/PUT /campers/1
  # PATCH/PUT /campers/1.json
  def update
    @camper = Camper.find(params[:id])

    if @camper.update(camper_params)
      redirect_to @camper
    else
      render 'edit'
    end
  end

  # DELETE /campers/1
  # DELETE /campers/1.json
  def destroy
    @camper.destroy
    respond_to do |format|
      format.html { redirect_to campers_url, notice: 'Camper record was deleted.' }
      format.json { head :no_content }
    end
  end

  private

  def set_camper
    @camper = Camper.find(params[:id])
  end

  def camper_params
    params.require(:camper).permit(
      :preferred_name,
      :dob,
      :pronouns,
      :essay,
      :notes,
      :shirt_size,
      :guardian_name,
      :primary_phone,
      :secondary_phone,
      :email,
      :secondary_email,
      :street_address,
      :second_address_line,
      :city,
      :state,
      :zip,
      :instrument,
      :instrument_first_choice,
      :instrument_first_choice_exp,
      :instrument_second_choice,
      :instrument_second_choice_exp,
      :waitlist,
      :additional_exp,
      :bringing_instrument,
      :personal_instrument,
      :dietary_restrictions,
      :food_restrictions,
      :additional_restrictions,
      :mental_health,
      :language,
      :income,
      :adults,
      :children,
      :age_group,
      :volunteering,
      :merchandise,
      :ethnicity,
      :reduced_lunch,
      :monetary_commitment,
      :years_attended
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campers_helper.rb
module CampersHelper
end

app/views/campers/_form.html.erb
<%= form_with model: @camper, local: true do |form| %>
  <% if @camper.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@camper.errors.count, "error") %> prohibited
        this camper from being saved:
      </h2>
      <ul>
        <% @camper.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <strong>CAMPER INFO</strong>
  </p><p>
    <%= form.label :preferred_name %><br>
    <%= form.text_field :preferred_name %>
  </p><p>
    <%= form.label "Date of birth" %><br>
    <%= form.text_area :dob %>
  </p><p>
    <%= form.label :pronouns %><br>
    <%= form.text_area :pronouns %>
  </p><p>
    <%= form.label :essay %><br>
    <%= form.text_area :essay %>
  </p><p>
    <%= form.label :notes %><br>
    <%= form.text_area :notes %>
  </p><p>
    <%= form.label :shirt_size %><br>
    <%= form.text_area :shirt_size %>
  </p>

  <p>
    <strong>FAMILY INFO</strong>
  </p><p>
    <%= form.label :guardian_name %><br>
    <%= form.text_field :guardian_name %>
  </p><p>
    <%= form.label :primary_phone %><br>
    <%= form.text_area :primary_phone %>
  </p><p>
    <%= form.label :secondary_phone %><br>
    <%= form.text_area :secondary_phone %>
  </p><p>
    <%= form.label :email %><br>
    <%= form.text_area :email %>
  </p><p>
    <%= form.label :secondary_email %><br>
    <%= form.text_area :secondary_email %>
  </p><p>
  </p><p>
    <%= form.label :street_address %><br>
    <%= form.text_area :street_address %>
  </p><p>
    <%= form.label :second_address_line %><br>
    <%= form.text_area :second_address_line %>
  </p><p>
    <%= form.label :city %><br>
    <%= form.text_area :city %>
  </p><p>
    <%= form.label :state %><br>
    <%= form.text_area :state %>
  </p><p>
    <%= form.label :zip %><br>
    <%= form.text_area :zip %>
  </p><p>
    <strong>INSTRUMENT INFO</strong>
  </p><p>
    <%= form.label "Instrument Assignment" %><br>
    <%= form.text_field :instrument %>
  </p><p>
    <%= form.label "First choice" %><br>
    <%= form.text_area :instrument_first_choice %>
  </p><p>
    <%= form.label "Experience with first choice instrument" %><br>
    <%= form.text_area :instrument_first_choice_exp %>
  </p><p>
    <%= form.label "Second choice" %><br>
    <%= form.text_area :instrument_second_choice %>
  </p><p>
    <%= form.label "Experience with second choice instrument" %><br>
    <%= form.text_area :instrument_second_choice_exp %>
  </p><p>
    <%= form.label "Willing to play any instrument if on wait list?" %><br>
    <%= form.select :waitlist, [['Yes', true], ['No', false]] %><br>
  </p><p>
    <%= form.label :additional_experience %>
    <%= form.text_area :additional_exp %>
  </p><p>
    <%= form.label "Bringing an instrument to camp?" %><br>
    <%= form.select :bringing_instrument, [['Yes', true], ['No', false]] %><br>
  </p><p>
    <%= form.label :personal_instrument %>
    <%= form.text_area :personal_instrument %>
  </p><p>
  <p>
    <strong>MEDICAL INFO</strong>
  </p><p>
    <%= form.label :dietary_restrictions %><br>
    <%= form.text_field :dietary_restrictions %>
  </p><p>
    <%= form.label :food_restrictions %><br>
    <%= form.text_area :food_restrictions %>
  </p><p>
    <%= form.label :additional_restrictions %><br>
    <%= form.text_area :additional_restrictions %>
  </p><p>
    <%= form.label :medical_conditions %><br>
    <%= form.text_area :medical_conditions %>
  </p><p>
    <%= form.label :mental_health %><br>
    <%= form.text_area :mental_health %>
  </p><p>
  <p>
    <strong>SOCIOECONOMIC INFO</strong>
  </p><p>
    <%= form.label :language %><br>
    <%= form.text_field :language %>
  </p><p>
    <%= form.label "Household income" %><br>
    <%= form.text_area :income %>
  </p><p>
    <%= form.label "Number of adults at home" %><br>
    <%= form.text_area :adults %>
  </p><p>
    <%= form.label "Number of children in home" %><br>
    <%= form.text_area :children %>
  </p><p>
    <%= form.submit %>
  </p>
  <p>
  <strong>ACCEPTANCE CRITERIA</strong>
  </p><p>
    <%= form.label :age_group%><br>
    <%= form.select :age_group, [['8-10', 'Stix'], ['11-12', 'Pix'], ['13-17', 'Mix']] %>
  </p><p>
    <%= form.label "Interested in volunteering?" %><br>
    <%= form.select :volunteering, [['Yes', true], ['No', false]] %><br>
  </p><p>
    <%= form.label "Interested in merchandise?" %><br>
    <%= form.select :merchandise, [['Yes', true], ['No', false]] %><br>
  </p><p>
    <%= form.label :ethnicity %><br>
    <%= form.text_area :ethnicity %>
  </p><p>
    <%= form.label "Receiving reduced fee lunch at school?"%><br>
    <%= form.select :reduced_lunch, [['Yes', true], ['No', false]] %><br>
  </p><p>
    <%= form.label :monetary_commitment %><br>
    <%= form.text_area :monetary_commitment %>
  </p><p>
    <%= form.label :years_attended %><br>
    <%= form.text_area :years_attended %>
  </p><p>
    <%= form.submit %>
  </p>
<% end %>

app/views/campers/edit.html.erb
<h1>Editing Camper</h1>

<%= render 'form', camper: @camper %>

<%= link_to 'Show', @camper %> |
<%= link_to 'Back', campers_path %>

app/views/campers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Campers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campers.each do |camper| %>
      <tr>
        <td><%= camper.preferred_name %></td>
        <td><%= link_to 'Show', camper %></td>
        <td><%= link_to 'Edit', edit_camper_path(camper) %></td>
        <td><%= link_to 'Destroy', camper, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Camper', new_camper_path %>

app/views/campers/new.html.erb
<h1>New Camper</h1>

<%= render 'form', camper: @camper %>

<%= link_to 'Back', campers_path %>

app/views/campers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Back', campers_path %> |
<%= link_to 'Edit', edit_camper_path(@camper) %>

<p>
  <strong>CAMPER INFO</strong>
</p><p>
  Preferred name:
  <%= @camper.preferred_name %>
</p><p>
  DOB:
  <%= @camper.dob %>
</p><p>
  Pronouns:
  <%= @camper.pronouns %>
</p><p>
  Essay:
  <%= @camper.essay %>
</p><p>
  Notes:
  <%= @camper.notes %>
</p><p>
  Shirt size:
  <%= @camper.shirt_size %>
</p>

<p><strong>FAMILY INFO</strong></p>
<p>Guardian: <%= @camper.guardian_name %>

<p>Contact info:</p>

<table>
  <tbody>
    <tr>
      <td><%= @camper.primary_phone %></td>
      <td><%= @camper.secondary_phone %></td>
    </tr>
    <tr>
      <td><%= @camper.email %></td>
      <td><%= @camper.secondary_email %></td>
    <tr>
      <td><%= @camper.street_address %></td>
      <td><%= @camper.second_address_line %></td>
      </td><td>
        <%= @camper.city %>,
        <%= @camper.state %>
        <%= @camper.zip %>
      </td>
    </tr>
  </tbody>
</table>

<p><strong>INSTRUMENT INFO</strong></p>
<p>Assigned to: <%= @camper.instrument %></p>
<p>First choice: <%= @camper.instrument_first_choice %></p>
<p>First choice experience level: <%= @camper.instrument_first_choice_exp %></p>
<p>Secon choice: <%= @camper.instrument_second_choice %></p>
<p>Second choice experience level: <%= @camper.instrument_second_choice_exp %></p>
<p>Willing to play any instrument? (waitlist qualifier): <%= @camper.waitlist %></p>
<p>Additional experience: <%= @camper.additional_exp %></p>
<p>Bringing an instrument to camp? <%= @camper.bringing_instrument %></p>
<p>Personal instrument: <%= @camper.personal_instrument %></p>

<p><strong>MEDICAL INFO</strong></p>
<p>Dietary restrictions: <%= @camper.dietary_restrictions %></p>
<p>Food restrictions: <%= @camper.food_restrictions %></p>
<p>Additional restrictions: <%= @camper.additional_restrictions %></p>
<p>Medical condtions: <%= @camper.medical_conditions %></p>
<p>Mental health: <%= @camper.mental_health %></p>

<p><strong>SOCIOECONOMIC INFO </strong></p>
<p>Household income: <%= @camper.income %></p>
<p>Language spoken at home: <%= @camper.language %></p>
<p>Number of adults at home: <%= @camper.adults %></p>
<p>Number of children at home: <%= @camper.children %></p>

<p><strong>ACCEPTANCE CRITERIA</strong></p>
<p>Age group: <%= @camper.age_group %></p>
<p>Interested in volunteering? <%= @camper.volunteering %></p>
<p>Interested in purchasing merchandise? <%= @camper.merchandise %></p>
<p>Ethnicity: <%= @camper.ethnicity %></p>
<p>Receiving reduced fee lunch at school? <%= @camper.reduced_lunch %></p>
<p>Monetary commitment: <%= @camper.monetary_commitment %></p>
<p>Number of years attending camp: <%= @camper.years_attended %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ThisIsCamp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>